### ISSUE TITLE
How to deal with ratiometric data?

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#102]
A colleague wants to try your pipeline using data imaged with Fura2 and she has two tif files for each wavelength. What would be the best way to deal with these types of data?

I tried running the pipeline with one of the files (340nm, increases when responding) and the performance was not good. Way too many ROIs detected, the ROIs of multiple cells were more usually merged than not etc.

**Comment by marius10p** [comment]
The default settings are optimized for gcamp imaging. You can try to adjust some of the settings until you find something that works better. Since the data is ratiometric, you should probably find a way to combine the two files into one and preprocess them divisively. Maybe data1/(data1+data2), or log(c+data1) - log(c+data2), where c is a small constant.

**Comment by carsen-stringer** [comment]
I'm going to close this issue due to inactivity, please comment if you want it reopened.
