### ISSUE TITLE
DOC: Please provide description of types of contributions you are (not) looking for

### ISSUE THREAD

**Issue by yarikoptic** [MouseLand/suite2p#1053]
### Issue with current documentation:

I got a PR https://github.com/MouseLand/suite2p/pull/1015 "rejected" with reasoning of "Thanks, but we don't accept this kind of pull request.".

### Idea or request for content:

As no information was provided of what kinds of PRs are to be or not accepted, so I or possibly others do not waste their time and effort, it would be great if README.md briefly outlined on the types of PRs people should (not) bother submitting.

**Comment by marius10p** [comment]
Thanks for the suggestion, I added this in the readme, also copying it here for reference: 

Note on pull requests: we accept very few pull requests due to the maintenance efforts required to support new code, and we do not accept pull requests from automated code checkers. If you wrote code that interfaces/changes suite2p behavior, a common approach would be to keep that in a fork and pull periodically from the main branch to make sure you have the latest updates.
