### ISSUE TITLE
Issue: adding new data to classifier

### ISSUE THREAD

**Issue by AlineRangolO** [MouseLand/suite2p#111]
Hi,

I'm trying to add new data to the classifier. However, when I run the pipeline with the updated classifier it doesn't work and I get this error:

![classifier_error](https://user-images.githubusercontent.com/44206586/47031328-981c4580-d13d-11e8-9f38-4be8142c92f8.PNG)

I was wondering if I'm not saving the updated classifier correctly. Usually I just do _Classifier -> Load -> Default Classifier_ and press the button _Add current data to classifier_

Thank you,
Aline

**Comment by marius10p** [comment]
We may have broken that workflow with one of the recent updates.  We will investigate shortly.

**Comment by carsen-stringer** [comment]
Oops good catch thanks! I've fixed the github version, and I'm going to make a new pip version now too. Because your default classifier is broken ('suite2p/classifiers/classifier_user.npy') you'll have to replace it with the built-in with the button in the gui menu "Classifier - Reset default to built-in".
