### ISSUE TITLE
Load registered data from the saved binary instead of the .tiff?

### ISSUE THREAD

**Issue by PhantomSpike** [MouseLand/suite2p#131]
Hi,

This might be just me being new to the Python Suite2P so apologies in advance if it's a silly question!

When you run the pipeline, you save a .bin file with the registered movie. Is it then possible to run the pipeline again on the same data, not doing the registration but just the ROI detection and extraction using that binary file? I see that there is an option to use .tiff or h5 file but not binary.

I guess I could tick reg_tif = 1 and that would save the registered .tif but the problem is that it makes the process slower and it duplicates the data unnecessary. Or I could also convert the .bin to h5 or tiff file.

Thank you!

Alex

**Comment by carsen-stringer** [comment]
Yeah if you run the pipeline again and haven't moved any of the data it should run without rerunning registration. You can for instance keep the run window open, check out the cells in the GUI, then choose another diameter, and click "RUN" again. If it still tries to register, you can force "do_registration"=0. I'll add this info to the GUI because I don't think we say this anywhere.

**Comment by carsen-stringer** [comment]
*add this info to the wiki

**Comment by PhantomSpike** [comment]
Oh, should have figured that out! Silly me!

Thanks Carsen!

**Comment by carsen-stringer** [comment]
no problem questions like these are good! reminds us to add more documentation :)

**Comment by generalciao** [comment]
@carsen-stringer wrote "If it still tries to register, you can force "do_registration"=0. I'll add this info to the GUI because I don't think we say this anywhere." But in the GUI the hover label do_registration says: "if 1, registration is performed if it wasn't performed already"

I understand the GUI hover text to mean that if the value is 1 but the data has already been registered by a previous run, registration will be skipped. But that's not what's happening in my case. Suite2p is re-reading the original data, rewriting the .bin files, and re-running registration when I run it a second time (from the command line, not GUI) with only changes to parameters relating to the segmentation step (anatomical vs. functional). 

Could you please clarify what needs to remain the same, and whether do_registration can/should be left at 1, if one wants to run suite2p multiple times (from the command-line, not GUI) without duplicating converting and registration?

**Comment by just-meng** [comment]
Hi, when I load the data.bin file using np.memmap, I get a 1d array. How can I read/reshape it correctly so it is in the shape of (nframes, Ly, Lx) for instance?
