### ISSUE TITLE
Type casting

### ISSUE THREAD

**Issue by alex-attinger** [MouseLand/suite2p#140]
Hi, my data is in uint16 format in hd5 files. The output of suite2p looks like it truncates values in weird ways when it casts the data to int16 in the utils.h5py_to_binary. I end up with bright cells appearing black in suite2p. What do you suggest to make my data (Neurolabware sbx files) compatible with suite2p? Would it be best to just divide by 2 (like you do in tiff_to_binary for the int 16 tiff files)? Or can I use the full range of int16 (-32768 to 32767)? Thanks

**Comment by carsen-stringer** [comment]
Hey sorry I only fixed this rescaling issue for tiffs that were uint16. I have added the same lines to the function "h5py_to_binary" in utils.py. But I don't have an uint16 hdf5 to test, so please let me know if the rescaling works.

Also I think Dario Ringach has written a suite2p specific conversion file for neurolabware: https://scanbox.org/2018/08/29/using-suite2p-with-scanbox/. You could divide by 2 and write an int16 hdf5 file instead of a uint16. But in theory the lines I just added should implement this fix for you.

**Comment by alex-attinger** [comment]
Thanks. Is there a specific reason why you chose to do everything in int16, and not, lets say uint16?

**Comment by marius10p** [comment]
Fft registration can produce negative values. Setting those to 0 would
introduce a bias.

**Comment by alex-attinger** [comment]
Forgot about that. Thanks for clarifying.
