### ISSUE TITLE
Very slow image registration

### ISSUE THREAD

**Issue by kthcwd** [MouseLand/suite2p#157]
Hi
I recently switched from the matlab to the python version of suite2P. I am having trouble with the speed of the analysis. We usually would be able to analyse a typical recording in <1 hour with the matlab version but for the same data it is taking >6 hours with the python version. I was initially using the GUI to set up the analysis and I am telling how many cores to use and it seems to be using them. The part that is taking the longest is the image registration - any ideas about what might be wrong or does it just take this long??
Thanks!
Kath

**Comment by kthcwd** [comment]
Actually I just saw an issue that this is probably related to about using all the cores... I will keep an eye on that issue

**Comment by carsen-stringer** [comment]
can you comment on that issue with your set up (OS and processor) and timings? and it's the registration part, not the binary writing. I think 'keep_movie_raw'=1 by default - set that to 0 so that the pipeline doesn't waste time making a copy of the binary file.

also choose fast_disk to be an SSD if you aren't already
