### ISSUE TITLE
Evaluating motion correction quality and z drift estimation

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#158]
I have a question about evaluating motion correction results from suite2p. It would be great to find some criterion for what constitutes a good vs. bad correction result. I am regularly viewing the registration metrics in the GUI and I can see that recordings that have obviously bad correction results / show a lot of drift throughout the recording show high peaks in the non rigid curve (px shift over PCs). Below I am showing the distribution of those peaks (max values for pixel shift over PCs for all recordings, all have been corrected with nonrigid option) in the different categories (nonrigid, rigid, nonrigid max). My first intuition was to define an (arbitrary) threshold and throw out sessions from the overall analysis that have non rigid max values > 5 (for example) for any of the PCs and combine that with some criterion (e.g. standard deviation for x / y offsets throughout recording). 
<img width="711" alt="mocorr" src="https://user-images.githubusercontent.com/7548928/54941924-4f5b8a80-4f2e-11e9-8c72-065a2e8f47c5.png">
Do you have any input on that? 
On a similar note (and sorry if I missed discussion / documentation here): Is the z drift estimation something that will be implemented in the python version? I think it would be very useful.

**Comment by marius10p** [comment]
I would not use the nonrigid max, because it can be skewed by particularly dark regions of the movie. I would use the nonrigid average to throw movies out. What do the failures of registration look like? In our data, we now only ever find blood vessel warping as nonrigid motion. 

The original z-drift estimation in the Matlab package was not something we could say for sure represented drift for everyone's recordings. If you use scanimage, we recommend the online drift correction using the estimator we contributed. 

In the python version, Z-motion can be seen in a certain type of PC, that looks like it contrasts the nucleus and cytoplasm of cells, kind of like the schematic from the Current Opinion review paper. We may be able to detect those automatically, so stay tuned...

**Comment by horsto** [comment]
Thanks. Failures are mostly occurring for sessions in which second channel doesn't have good enough label. I hardly use the first, active channel for motion correction since overall labeling is sparse and non active cells completely disappear into darkness. 
I saw both the figures and the scanimage implementation - I am eager to try that at some point. Very much looking forward to an automatic detection in the python version!
