### ISSUE TITLE
Matching FOV across different imaging sessions

### ISSUE THREAD

**Issue by gtfioreze** [MouseLand/suite2p#159]
Hi,

First thank you for this great tool.

I used to run the matlab version of suite2p and match FOV across different imaging sessions with registers2p. Do you guys have plans to implement a similar plugin for the Python version?

Thank you!

**Comment by carsen-stringer** [comment]
we are interested in adding this capability. Henry Dalgleish wrote "registers2p" and has yet to port it to python. 

You can try running all your recordings together (add all the separate folders to data_path). This has worked well for people who have automated online registration on their microscope to register day by day (scanimage 2018b (free) offers this capability). I highly recommend checking this out - we have contributed to a module in that software for online Z-correction that has greatly improved our recording quality.

However, if there are significant non-rigid shifts between days (angle changes etc) and low SNR I've found that concatenating recordings and running them together will not work so well.

**Comment by ransona** [comment]
Just in case it's useful to anyone I've uploaded a version of the roi matching tool we developed for use with the output of the Python version of Suite2p. This tool is written in Matlab as we still do our analysis there after processing the data in the Python Suite2p. Wasn't sure if gtfioreze is looking to go pure Python or not.  I've not really used Henry Dalgleish's tool so I don't know how easy it is to modify it to process the Python Suite2P data. 

Our code has only been used by my lab so I'm sure his software is a lot less buggy! I think we rip off Henry's general method if I remember rightly (using the Matlab CPSelect and imwarp to map the ROI masks on to one another). It is focused on being very sure you have matching cells rather than high throughput and so after automatic detection includes a manual inspection step where you check the cell looks the same across sessions by eye.

As I say it hasn't been widely tested but might be useful to someone and happy to fix any bugs that crop up. There is a help file in the repository.
https://github.com/ransona/ROIMatchPub

**Comment by carsen-stringer** [comment]
thanks Adam! I've added this info to this wiki page: https://github.com/MouseLand/suite2p/wiki/Multiday-recordings. In your package, can you please make the help file a README.md? It will make it easier for people that way I think.

**Comment by ransona** [comment]
no probs, I've done that now!

**Comment by gtfioreze** [comment]
Thanks for sharing! That's exactly what I was looking for!
Cheers,

**Comment by carsen-stringer** [comment]
we've added a new view 'max_proj' that looks pretty sweet, that might be useful for your purposes @ransona et al . please try the latest version if you want to check it out, and see the installation instructions on the readme

**Comment by ransona** [comment]
brilliant thanks! a couple of things related to this..
1) has the way the roi pixels x and y position is saved changed? i think it is relative to the full uncropped frame now rather than taking into account the cropping due to registration? 
2) is this 'max_proj' calculated after some temporal averaging? might be worth doing this if not as I get quite a lot of bright pixels which I think are just single frame noise rather than brightness due to calcium signals.
many thanks. 
Adam

**Comment by carsen-stringer** [comment]
sorry I didn't answer this sooner
1. yes the x and y position are relative to the full frame not the cropped frame
2. 'max_proj' is computed on binned frames, with a bin size of ops['tau']*ops['fs']

**Comment by nickdelgrosso** [comment]
I’m closing this issue because it seems as though a satisfactory solution was found, and the discussion has been inactive for a few months. Please reopen if you still encounter this issue in the latest version of suite2p.
