### ISSUE TITLE
Memory error upon running Suite2p

### ISSUE THREAD

**Issue by Benjamin-Pasternak** [MouseLand/suite2p#160]
I installed suite2p using anaconda command prompt pip install on both Mac and Linux, and Google cloud instance. I tested suite2p on both our own tiff files and those that were provided as examples in the documentation. I created the save_path and fast_disk as instructed. In both cases, I received the below memory error. 

Found 6 tifs
===== 2019.03.26 11:03:25 =====
>>>ERROR<<<
Traceback (most recent call last):
  File "/home/tomi/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tomi/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tomi/anaconda3/lib/python3.7/site-packages/suite2p/__main__.py", line 32, in <module>
    suite2p.run_s2p.run_s2p(ops, db)
  File "/home/tomi/anaconda3/lib/python3.7/site-packages/suite2p/run_s2p.py", line 146, in run_s2p
    ops1 = utils.tiff_to_binary(ops)
  File "/home/tomi/anaconda3/lib/python3.7/site-packages/suite2p/utils.py", line 253, in tiff_to_binary
    im = im / 2
MemoryError
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
What are the dimensions of your tiffs? utils.tiff_to_binary reads in 500 frames at a time - is your RAM usage reaching 100%?

**Comment by drow339** [comment]
The dementions on the tiffs that I was using are 788 × 662. They are the example tiffs from Suite2p doccumentation (the ones on th google drive linked).  I have not checked ram utalization, however I am running Suite2p on the cloud and have trained other machine learning programs without this issue. Probing around in the program leads me to believe it is a static type error, but I'm not sure what could be causing it.

**Comment by carsen-stringer** [comment]
We have an option ops['batch_size'], and it is now also used in the utils.tiff_to_binary function. You can set this to something low (maybe 100) and see if it works. This fix is currently in the development branch (**sparse_mode**) so you will have to 'git checkout sparse_mode' to try it out.

**Comment by turnerbd** [comment]
I'm also having this issue. I've tried this on several computers with varying amounts of RAM with no luck. I've tried disabling registration since my samples are stationary (slices) and I've also tried on single images or very small tiffs (50 images total) but this also did not work. Oddly enough it barely utilizes any RAM when I execute it. Any suggestions? 

===
>>>ERROR<<<
    exec(code, run_globals)
  File "C:\Users\Brandon\Anaconda3\lib\site-packages\suite2p\__main__.py", line 32, in <module>
>>>ERROR<<<
    suite2p.run_s2p.run_s2p(ops, db)
  File "C:\Users\Brandon\Anaconda3\lib\site-packages\suite2p\run_s2p.py", line 146, in run_s2p
>>>ERROR<<<
    ops1 = utils.tiff_to_binary(ops)
  File "C:\Users\Brandon\Anaconda3\lib\site-packages\suite2p\utils.py", line 249, in tiff_to_binary
>>>ERROR<<<
    im = imread(file, pages = range(ix, ix + nfr))
  File "C:\Users\Brandon\Anaconda3\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1234, in imread
>>>ERROR<<<
    return tif.asarray(**kwargs)
  File "C:\Users\Brandon\Anaconda3\lib\site-packages\skimage\external\tifffile\tifffile.py", line 1502, in asarray
>>>ERROR<<<
    result = pages[0].asarray(memmap=memmap)
  File "C:\Users\Brandon\Anaconda3\lib\site-packages\skimage\external\tifffile\tifffile.py", line 2527, in asarray
>>>ERROR<<<
    result = result.astype('=' + dtype)
MemoryError
Interrupted by error (not finished)

**Comment by carsen-stringer** [comment]
I'm not sure, this looks like a problem with scikit-image tifffile. Can you see if you can load your tiff with scikit-image in a jupyter-notebook for instance?
~~~
from skimage.external.tifffile import imread, TiffFile

# this will load all frames from the tiff
im = imread(file, fastij = False)
~~~

**Comment by carsen-stringer** [comment]
@drow339 FYI suite2p is a CPU based algorithm and does require some RAM to run (depending on the batch_size). 8GB should be fine with a batch_size of 200, but it will be slower to run. I'd recommend at least 32GB of RAM so you can increase the batch_size to 500 or more for speed.

**Comment by turnerbd** [comment]
> 
> 
> I'm not sure, this looks like a problem with scikit-image tifffile. Can you see if you can load your tiff with scikit-image in a jupyter-notebook for instance?
> 
> ```
> from skimage.external.tifffile import imread, TiffFile
> 
> # this will load all frames from the tiff
> im = imread(file, fastij = False)
> ```


@carsen-stringer No, it does not let me open the demo tiff files in Jupyter (see attached). 

![imread error](https://user-images.githubusercontent.com/50340137/57990017-7044e580-7a70-11e9-8bfb-c66816944638.PNG)

**Comment by turnerbd** [comment]
@carsen-stringer I managed to solve the issue. I had been running Suite2p with in an environment with a 32bit version of Python which cannot utilize scikit-image/tiffile.

**Comment by carsen-stringer** [comment]
@drow339 I'm sorry about the trouble you were having, scanimage-tiff-reader wasn't doing garbage collection for us like scikit-image does. We've added the garbage collection to the code, so that this shouldn't happen anymore. please try the latest version, and see the installation instructions on the readme

**Comment by windgrazer** [comment]
@carsen-stringer I have been experiencing a similar Memory Error as seen in the screenshot below:

![Error message](https://user-images.githubusercontent.com/26172299/60578747-51967600-9db4-11e9-836b-72b185a30920.jpeg)

I have been using ver. 0.5.5 for all of my previous runs prior to this error. I tried to uninstall and pip install the latest version again but to avail. My computer runs on 16GB RAM and the image contains 150 frames (compared to the 1000 frames for prior images) but has a higher resolution than before.

**Comment by carsen-stringer** [comment]
You may have to reduce your **batch_size** for this part of the pipeline to not use too much memory (maybe to 50 if your frames are really big). maybe we'll set a different batch_size for this part of the pipeline in the future (because you had no memory errors in registration or writing the binary).

**Comment by carsen-stringer** [comment]
I'm going to close this due to inactivity, please comment if it's not resolved and you'd like us to look into it further

**Comment by Aleksandra-Gavrilova** [comment]
Hi! I have also faced the problem with the errors during running Suite2p, but I'm not sure what exactly is wrong with the process - I have 5000-frames tiff file, the registration went okay, but once it started to select ROIs, it crashed... Could you please suggest what can be done in this case and what was the cause of it? Thank you!
I'm attaching the screenshot with the error type.

![image](https://user-images.githubusercontent.com/81811504/236394990-996f07ba-2d65-41b6-a7db-96bbe00f4cf1.png)

**Comment by jjm2144** [comment]
I also am encountering a similar error using a new computer with 32+gb RAM and a GPU only selecting a handful of ROI's on a small data set. Please reopen
