### ISSUE TITLE
Python executable pointing to python2

### ISSUE THREAD

**Issue by kvoit** [MouseLand/suite2p#187]
I have installed suite2p via pip on Ubuntu 18.04 and I am running into some trouble:

The code builds system calls by string concatenation in two places using `python` as the command:
```
gui.py:     self.process.start('python -u -W ignore -m suite2p --ops ops.npy --db db.npy')
run_s2p.py: os.system('python '+ ops['clean_script'] + ' ' + fpathops1)

```

According to [PEP 394](https://legacy.python.org/dev/peps/pep-0394/), `python` should point to python2, which it does on my Ubuntu system as clearly [stated by Ubuntu](https://wiki.ubuntu.com/Python/3). This leads to the effect that when I hit the "RUN SUITE2P" button, I get the error that the module suite2p was not found, because python2 was executed.

I could fix this by replacing `python` with `python3` in above-mentioned positions.

Is this a bug, why do I seem to be the only one affected and what is the indented way to deal with this?

**Comment by carsen-stringer** [comment]
I'd recommend making an environment with Anaconda and within that python will point to python3. We always use conda (and recommend doing so to others) <- see updated readme on this

**Comment by kvoit** [comment]
I am not particularly proficient in Python, but is there a particular reason to disregard PEP 394?

**Comment by carsen-stringer** [comment]
I would recommend using anaconda if possible so that numba and mkl_fft are optimized. the mkl_fft pip for instance is out-of-date (I've bugged them about it). we'll post timings for things soonish and then you can compare and see if things are working right

I will change the code but use a python3 conda environment going forward and keep in mind python2 will no longer be supported in 2020, so I think this won't be a problem soon :)

**Comment by kvoit** [comment]
Ok, thanks for the change and the advice! Will change over.
