### ISSUE TITLE
cropped FOV in ROI detection

### ISSUE THREAD

**Issue by schoki0710** [MouseLand/suite2p#207]
![Suite2P_ROIcroped](https://user-images.githubusercontent.com/51796857/60967479-0d0e5b80-a31b-11e9-87f7-232378b015a7.jpg)

We noticed that the field of view often gets cropped into a rectangle smaller than the original images, so then the cells at the periphery cannot be detected. Is there any parameter I should modify to solve this issue?

**Comment by carsen-stringer** [comment]
yeah this is probably because you might have some frames with large XY shifts and we crop based on these shifts. you can view the shifts in 'view registered binary' view. we have a parameter to determine which frames to exclude when deciding on the cropped size `ops['th_badframes']` - reduce this and more frames will be excluded and therefore there should be less cropping
