### ISSUE TITLE
Non rigid motion correction jerky result

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#219]
I am using nonrigid motion correction on a regular basis and it works really well for my data - it's magic. However, I am encountering problems with a stack which seems like the ideal case for motion correction (has almost no nonrigid, mostly rigid offsets, contrast seems comparably high compared to other videos), but results in very jerky motion artefacts after correction. There is almost no motion in the original video, so I was wondering where this comes from. Here are some frames from the second, structural channel on which I correct, after motion correction: https://imgur.com/a/DMUx7gN (sorry, the gif is a bit fast). You can clearly see this artefact of the whole frame jumping around. 

Things I have tried so far: 
- change `nimg_init` to larger values (up to 800)
- change registration `smooth_sigma` from 1.15 up to 4
- change nonrigid `block_size` : I had it at [80,120] (which worked fine), changed to larger blocks [100,150]
- nonrigid `snr_thresh`: decreased to 1.2 from 1.5
- nonrigid `maxregshiftNR`: changed to 10.0 from default
... and tried different combinations of those parameters. 
Those were settings which I naively thought could change things, but they all result in the same artefact.  

Have you seen something like that before and do you have an idea where it comes from? I am happy to upload that channel if you want to check yourself. 
Thanks!

**Comment by horsto** [comment]
After switching to `nonrigid = 0` the artefact persists: https://imgur.com/1vFJWzY (left: original video, right: video after motion correction)

**Comment by carsen-stringer** [comment]
I think in this case you may need to high pass filter in space (1Preg=True, spatial_hp=50) because there aren't a lot of small features for the registration to use.

Also @jwdegee implemented some useful enhancements to make registration more robust that are available in the github version in the GUI run window, but your data is pretty high SNR:
- **two_step_registration**: (*bool, default: False*) whether or not to run registration twice (for low SNR data). *keep_movie_raw* must be True for this to work.
- **smooth_sigma_time**: (*float, default: 0*) standard deviation in time frames of the gaussian used to smooth the data before phase correlation is computed. Might need this to be set to 1 or 2 for low SNR data.

**Comment by carsen-stringer** [comment]
are you using bidiphase corrections? there was a bug with this that was shifting things crazily like this! I've pushed some code that should have fixed it today

**Comment by horsto** [comment]
Yes, indeed I am using that function (bidiphase), which seems to mostly run fine. I will try again, thanks!

**Comment by carsen-stringer** [comment]
i'm going to close this for now because I think that was the bug
