### ISSUE TITLE
ops for RGECO

### ISSUE THREAD

**Issue by tai-heinzerling** [MouseLand/suite2p#233]
Hello,

I am a graduate student researcher in the lab of Dr. David McCormick at the University of Oregon. You have been of great help to my lab-mates with their questions on suite2p in the past and so I was wondering if you might have some advice for me. I have recently started working with mice expressing a red calcium indicator, jRGECO1a, in excitatory neurons. I am getting decent cell detection in suite2p, but not as good as with GCaMP. Do you have any thoughts on parameters I might tweek to get it to work better, or have you heard of anyone else using suite2p with a red indicator?  jRGECO1a has similar kinetics to GCaMP6f I believe, with a half decay time of about 150 ms. Is this the value I should use for tau? I have been unsure whether tau is the half decay or the ~2/3 decay time.

Thanks for any input you can provide!

Best,
Tai

**Comment by ronan-dasilva** [comment]
Hey Tai,

I have been using S2P with jRGECO1a and so far I have been having great results.

In my experience, what matters more for RGECO is that you optimize your acquisition setup rather than your ops in S2P, since S2P doesn't really care what is your fluorophore (all it sees are the signals you collected).

Here's one example screenshot of detected cells in mouse V1 after imaging with jRGECO1a. 
![image](https://user-images.githubusercontent.com/49962552/64358633-d2e8cf80-cfd4-11e9-90f6-c3d02a8de493.png)

My acquisition setup were:
- Laser wavelength: 1085nm
- Laser power: ~2.00 mW
- Laser attenuation: 75% (actually more since we dump out about half of our laser initial power)
- Frame rate: 15.49 Hz
- Frame size: 512 x 796 (important if you want to know the precise pixel dwell time)
- Magnification: 2.0 (also important to calculate dwell time)

Hope this helps! Let me know if you want to know anything else.

Ronan

**Comment by tai-heinzerling** [comment]
Hi Ronan,

Thank you for your prompt and thorough response! I will work on my acquisition setup. 
Can you also clarify for me what exactly the tau parameter means in suite2p? Is it half decay or the ~2/3 decay time?

Thanks,
Tai

**Comment by carsen-stringer** [comment]
thanks ronan for providing this info! I haven't used RGECO myself so I don't have any insights on this.

yes it's the half-decay. we are using the oasis algorithm from this [paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005423)

**Comment by Yasmine-Ayman** [comment]
Hi Ronan, I am dealing with a similar issue where I do not get more than 60 cells in cortex for jrgeco1a  with the latest suite2p. for acquisition, what power did you have at the objective? It can't be 2mW for 2-photon imaging at least. Currently I have around 100mW at the objective, 30 Hz frame rate, 1.5 zoom and 512x512 frame size. Do you have any updates on what worked best for you for jrgeco1a with suite2p? thanks so much!
