### ISSUE TITLE
Criteria to exclude frames for further analysis

### ISSUE THREAD

**Issue by lee-ty** [MouseLand/suite2p#245]
Hello, 

Thanks so much for the great software! I've got some questions regarding setting some criteria to exclude frames that have too much motion during an imaging session. 

I've had a look at the registration metrics, and seems like the values for rigid and nonrigid pixel shifts could be potentially useful for this, as in some PCs we can see some z-drift. Is there a way to know which frames contribute the most to those PCs to exclude them from further analysis please? Also what values for the rigid and nonrigid shift would you suggest that it's too much please?

I've also considered to play with the badframes threshold but am not entirely sure what range of values are reasonable. May I ask how you determine the threshold please?

Many thanks in advance!
Tai-Ying

**Comment by carsen-stringer** [comment]
In the more recent versions of suite2p, you can also see the timecourse of the motion PCs. This should let you get a sense of whether you have slow or fast drifts, and how many frames are affected by it. ops['tPC'] contains the timecourses. These are computed on an evenly-spaced subset of frames (not the whole movie) - if 5000 frames are computed then the frames are spaced nframes/5000 apart.

If you are seeing z-drift and it's slow, then I'd recommend splitting the recording in half in time and checking that you get the same results depending on which half of the data you base your model/analyses on. Fast z-drift is a little more tricky. We take a z-stack at the beginning of each recording and then align each frame to the z-stack if we need highly accurate z-movement estimates across time. You can also use ops['tPC'] as a proxy for this but you'd have to compute it for all the frames.

For the bad_frames, those are determined as outliers of the correlation between the registered frame and the target image. If that correlation is too low, it's likely because the movement has changed the imaging plane too much. The threshold is just for excluding frames from the calculation of registration limits. It is set in relation to the average correlation of neighboring frames and you can scale it up and down with this variable:
```
        'th_badframes': 1.0, # this parameter determines which frames to exclude when determining cropping - set it smaller to exclude more frames
```

You can just take the badframes variable from ops and exclude frames posthoc.

**Comment by carsen-stringer** [comment]
I am going to close this due to inactivity, please reopen if you have more questions
