### ISSUE TITLE
ROI detection--Active cells not detected

### ISSUE THREAD

**Issue by foustoukosg** [MouseLand/suite2p#262]
Hello,

I think I have a issue with ROI detection in certain cases in my calcium data.

It seems that sometimes some very good cells are not detected as ROIs for reasons which are not very clear to me.

You can see example of this type of this behavior in the attached images. The cell is pretty active also (as I can see by eye in the tiff movie) but somehow is not included in the detected ROIs. In the correlation map it seems like there must a be an ROI there and in the max projection image the cell seems to be really bright and beautiful.

I have tried up to now to change between sparse mode true of false, force the spatial scales or reduce the threshold for detection but non of those seems to improve the detection. The only parameter which seems to have solved the problem sometimes is increasing the number of binned images for ROI detection (from default 5000 to 10000). However, in most of the cases using the maximal possible number (limited by the RAM of the computer) does not seem to solve it.
 
Would it be possible to get a suggestion of which parameters I could trick (If it is possible at all) to get those cells included in the detected ROIs.

Thank you very much in advance.
Georgios Foustoukos

![ROIs](https://user-images.githubusercontent.com/34298206/69498132-c5145d80-0ee4-11ea-88f7-56818de13a6a.PNG)

![Correlation_map](https://user-images.githubusercontent.com/34298206/69498136-cb0a3e80-0ee4-11ea-8e06-e13b161912e2.PNG)

**Comment by carsen-stringer** [comment]
Thanks for all the info and the images, there is a clear peak there in the correlation map - therefore the algorithm should extract a cell there if the threshold_scaling is sufficiently low (it looks like it is considering other detected ROIs).

I think maybe this cell is detected but is on the NOT CELLS side of the GUI because the classifier misclassified it. You can look at the NOT CELLS by clicking the button at the top of the GUI. You can flip all the cells to the left side ("CELLS" side) by setting the classifier, cell prob=0.0 and pressing enter (this text entry box is on the left side of the GUI). Then you can see easily if there was indeed an ROI there.

**Comment by foustoukosg** [comment]
Hello,
Thank you very much for the answer.

However, I have checked this and there seems to 0 cells in the NOT CELLS side. Even if I put the probability of the classifier at 0 it stills seems to be undetected. 

Here is the full image I see in the GUI.

Thank you so much for your time.

Best regards,
Georgios 

![ROIs](https://user-images.githubusercontent.com/34298206/69740142-33e9f480-1139-11ea-99b8-04317c0c065e.PNG)

**Comment by carsen-stringer** [comment]
Hmm there's a new **output** option called "preclassify", this means that the pipeline completely throws out cells that the classifier doesn't like. Did you set this above 0.0? Try setting this to 0.0 in the GUI please if you hadn't before. Unfortunately the default might not be 0.0 in one of the releases.

**Comment by carsen-stringer** [comment]
I am going to turn off preclassify by default in the next pip release. I am going to close this issue for now, please comment if you still have issues
