### ISSUE TITLE
Super-resolution mean image?

### ISSUE THREAD

**Issue by djoshea** [MouseLand/suite2p#276]
Hi Carsen, Marius, very much appreciate your hard work on this. 

Quick question - in the biorxiv paper you mention using the subpixel alignment to create a super-resolution mean image, as shown in Supp. Fig 3.  Are you still using this approach? If so, is this what's being shown in the GUI? More to the point, is there any way to access / export / recompute it if I've used 'subpixel' == 10? 

I might be missing something obvious but I haven't noticed any arrays that aren't the same size as my input images.

Thanks!

**Comment by carsen-stringer** [comment]
In the latest version of suite2p we do pixel-level rigid registration and then subpixel-level nonrigid registration (with a resolution of 0.1 = 1/subpixel, but that is value is now hard-coded, that variable can't changed). Because the subpixel part is non-rigid it is not straight-forward to recreate the super-resolution image. If you want to know the shifts for each block, they are in ops['yoff1'] and ops['xoff1'].

The mean image in the GUI is the mean across all registered frames so it should be decent quality.

**Comment by djoshea** [comment]
Great, thanks!
