### ISSUE TITLE
cell merging if high correlation and proximity

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#28]

**Comment by marius10p** [comment]
This should be done right after cell detection, comparing the codes for two ROIs and their proximity status. If they pass a threshold, merge and continue iteratively.

**Comment by marius10p** [comment]
Could also do this iteratively and allow the other ROIs to adjust.

**Comment by marius10p** [comment]
The codes are probably very different, otherwise they would have been merged in the first place, which the sequential expansion of the ROI ensures. 

The problem we really want to solve is that multiple ROIs overlap to account for the same cell. So we remove ROIs that have too many overlapping pixels, just before the refinement step. Default threshold is now 0.75. While high, this seems sufficient given that the masks are already quite wide because of the smoothing.
