### ISSUE TITLE
saving binary to save_path when using fast_disk? 

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#304]
I wonder if it is possible to save the binary file to the save_path after running the pipeline using a fast_disk.

Currently I am looping through multiple experiments using the same fast_disk. The binary file is overwritten every time I run another experiment so the only binary that is kept is the one from the last file ran. 

Is it possible to move the binary to the save_path when done?

**Comment by carsen-stringer** [comment]
hmm this would be slow so I don't know if it should be default behavior but we have a flag that when True copies it

**Comment by carsen-stringer** [comment]
I've added this to the github, it's called 'move_bin' and it's in the run GUI. going to close this issue, please comment if it's not working

**Comment by just-meng** [comment]
Hi Carsen, 

if 'move_bin' is False, suite2p won't find the binary file when rerunning (e.g. for cell detection). It would be nice to either (1) add this information to the doc, or what I would personally welcome, to (2) search for the binary file in the 'fast_disk' directory if not found in 'save_path'. The second option would be a problem if the user keeps overwriting the fast_disk with new binary files. In my case I treat 'fast_disk' the same way as 'save_path0' and make sure that each binary file ends up in its own fast_disk directory because I have the intention to rerun suite2p multiple times and wish to load from the binary files. 

Cheers,
Meng
