### ISSUE TITLE
Using suite2p to detect entire microglia cells

### ISSUE THREAD

**Issue by johnw-25** [MouseLand/suite2p#311]
I have been trying to adapt suite2p to the different cell type with some success! However, I'm attempting to alter the parameters to capture entire microglia cells which has proved to be difficult. Do you have any suggestions on how to change the parameters to solve this problem or is this not possible? 

I pasted a reference image that shows a cell where Suite2p has detected two ROIs within the cell. My goal is to have Suite2p detect the entire cell as one ROI. Our microglia cells express eyfp and GCaMP5G. Thanks!

![sample-data](https://user-images.githubusercontent.com/62902060/77946932-570be880-7280-11ea-9b21-36c631886627.png)

**Comment by carsen-stringer** [comment]
Can you post an image of the ROI's overlaid? (like a screenshot from the GUI). Suite2p performs "functional" not "anatomical" segmentation, so if pixels are not coactive then they will not be put into the same ROI.

**Comment by johnw-25** [comment]
Hi Carsen,

Yes I can. It is a different image than posted but it demonstrates what we are trying to do. I also post the settings that are being used in case you have some additional insight. Thank you for your help!
![roi_overlay](https://user-images.githubusercontent.com/62902060/79078299-bb896780-7cc4-11ea-8803-cfa4e929ae60.JPG)

![params](https://user-images.githubusercontent.com/62902060/79078303-bfb58500-7cc4-11ea-859e-041d8409f87b.JPG)

**Comment by nickdelgrosso** [comment]
This issue appears to be inactive.  Closing the issue; it can be reopened when conversation around the topic begins again.

**Comment by penguingiraffe2** [comment]
Hello! 
Hoping to maybe reopen this discussion given all the updates that have gone into suite2p since it was last brought up. 
We have been doing some dynamic calcium imaging in microglia using GCaMP 5s... After having really amazing success with the software on neurons, we were hoping to use it again for the microglia imaging. 

Wondering how you would suggest parameterizing the GUI for non-neuronal shaped ROIs?  

Will of course update if I have any success trying things out
