### ISSUE TITLE
suite2p installation incompatible with new scikit-image==0.17.2

### ISSUE THREAD

**Issue by Saksham20** [MouseLand/suite2p#324]
There seems to be an incompatibility with the latest release of skimage=0.17.2. Due to which when I create an env using the environment.yml with conda and then do `import suite2p` :
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Saksham\Anaconda3\envs\suite2p\lib\site-packages\suite2p\__init
__.py", line 1, in <module>
    import suite2p.run_s2p
  File "C:\Users\Saksham\Anaconda3\envs\suite2p\lib\site-packages\suite2p\run_s2
p.py", line 5, in <module>
    from .io import tiff, h5, save
  File "C:\Users\Saksham\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\__i
nit__.py", line 1, in <module>
    from . import utils, h5, save, tiff
  File "C:\Users\Saksham\Anaconda3\envs\suite2p\lib\site-packages\suite2p\io\tif
f.py", line 12, in <module>
    from skimage.external.tifffile import imread, TiffFile, TiffWriter
ModuleNotFoundError: No module named 'skimage.external'```
Can you update the dependency?

**Comment by scottclowe** [comment]
Because tifffile now has wheels available for all OSes, skimage no longer (https://github.com/scikit-image/scikit-image/commit/f7649eff35e9672a20f340bdf29f71c2e2dcad23) ships with its own copy of tifffile. Hence it was removed from the skimage.external module (in fact, the whole external module was removed because it was the only external package). suite2p should follow suit and move to using the official tifffile package as a dependency instead of trying to take it out of skimage.

**Comment by carsen-stringer** [comment]
thanks all for the info! I've upgraded the package and removed scikit-image dependencies. let me know if it works now

**Comment by samihassan84** [comment]
Hi Carsen,
the tifffile issue seems to persist with the latest version (suite2p 0.7.3). It works after manually installing tifffile to the environment

**Comment by carsen-stringer** [comment]
oops added in the dependency thanks for catching this!
