### ISSUE TITLE
add developer's environment.yml (include doc dependencies)

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#333]

**Comment by nickdelgrosso** [comment]
I added a requirements_dev.txt file that mentions just the dev requirements and can be installed from pip.  The installation instructions are updated on the readme file. 

This allows devs to just add specific tools that users don't need (right now, just pytest, but soon sphinx and others) and keeps every dependency specified at a specific place.  However, it's not an ideal solution.  It's still possible for users to have incomplete installs during the upgrade process, most notably, because the only release pathway is via pip, which can't manage the conda dependencies.  The only way I see to solve this is to host suite2p on conda, so that changes in the environment.yml file have an effect on updates.

**Comment by nickdelgrosso** [comment]
Details for this issue on the pull request: #332

**Comment by carsen-stringer** [comment]
for now I think we will continue to use the pip package manager, with an environment.yml file in the repo.
