### ISSUE TITLE
timing functions with and without caching

### ISSUE THREAD

**Issue by carsen-stringer** [MouseLand/suite2p#426]
why do we need cached_property's in stats.py? why can they not be saved as attributes? these will be saved into the 'stat.npy' file

**Comment by nickdelgrosso** [comment]
Hi Carsen,

methods ensure both correctness and seperability within a class, as well as make it possible to delay computation until the computation is actually needed.  By implementing methods as properties, the public interface can feel like an attribute without accidentally violating correctness through internal changes (e.g. ypix or xpix being assigned) or external changes (e.g. r_mean_squared being assigned).  A few of these properties are often depended on by others and can be expensive to calculate, so selectively assigning a few of them as cached properties (a built-in feature of Python 3.8, added as an installed module for Python 3.7) ensures that recomputation doesn't happen often for those few (just ROI.r_mean_squared() and ROI.fit_ellipse()).

The stat.npy file should not be related to this implementation whatsoever.

Best wishes,

Nick

**Comment by marius10p** [comment]
Nick, I don't think this is a place where features need to be cached, and there shouldn't really be anywhere in the code  where things are re-computed, unless you've encountered some outlier use case. 

I am not sure that's what's happening here, but note that the ROIs can change as a consequence of post-processing operations. In that case, caching would result in incorrect computations, because the ROI pxiels change, but their r_mean_squared doesn't, and it should.

**Comment by nickdelgrosso** [comment]
Okay, that's good news.  Will remove the caching.

**Comment by chriski777** [comment]
Fixed in #434
