### ISSUE TITLE
Updating ophys.nwb following manual labelling

### ISSUE THREAD

**Issue by maxseppo** [MouseLand/suite2p#437]
Similar to [issue 419](https://github.com/MouseLand/suite2p/issues/419), would it be possible to save the results of manual labeling of ROIs as cell/not cell in the iscell array of the NWB output?

**Comment by chriski777** [comment]
Yes, this is possible. I'll start on implementing this

**Comment by chriski777** [comment]
Hey @maxseppo and @kiroul, just wanted to follow up with you both on this. Unfortunately, I'm not too familiar with the GUI to proceed on this issue. This issue will stay open though so that other team members who are more familiar with the GUI code can discuss this with y'all.

For the time being, I thought it might be helpful to notify you both that there is still a way to save the results of manual labeling of ROIs into NWB output. Here are some instructions that hopefully help out: 

1. Proceed with manual labeling then save/quit. 
2. In a script/notebook, you can then use the following code block: ``` from suite2p import io; io.save_nwb("insert_PATH_to_suite2p_output_folder")```

A nwb file should then be saved within the save_folder passed above.

**Comment by kir0ul** [comment]
Indeed that's exactly what we do at the moment :slightly_smiling_face:

**Comment by kir0ul** [comment]
Follow up PR: https://github.com/MouseLand/suite2p/pull/650
