### ISSUE TITLE
View registered binary: left and right arrows keys increase by 15 in each press

### ISSUE THREAD

**Issue by fangyue1992** [MouseLand/suite2p#484]
When playing the registered binary movie, left and right arrow keys indeed can move the slide bar but each time of pressing the key leads to 15 images increase. Is there any way of pressing key once only leads to 1 image increase?

**Comment by chriski777** [comment]
Hey @fangyue1992, as of now, I don't believe there is a way (just using the GUI) to modify the number of frames affected by pressing the left/right key. The number of frames changed by each press will always depend on the length of a video. Longer videos may have each left/right key more than 15 frames and shorter videos may have changes fewer than 15 frames. 

There is definitely a _way_ to change the code so that you should be able to do this. However, I don't believe code changes to the GUI will happen for a while so this may take a bit of time. :(

There is a small workaround that you can use if it doesn't impede your workflow too much. If you set `reg_tif` (and `reg_tif_chan2`if you have a second channel)  under the output settings to 1 before you run suite2p,  suite2p will output tifs of the registered binary file to their respective plane folders. You can then use ImageJ to look at these tifs 1 frame at a time.

**Comment by fangyue1992** [comment]
> ork

Hi Chriski, okay, I will use your idea to view the output registered images! Thanks so much for your advice!
