### ISSUE TITLE
Regression Test Issue with Ubuntu 18.04 bionic

### ISSUE THREAD

**Issue by chriski777** [MouseLand/suite2p#506]
For some reason, our tests with `reg_tif=True` fail on machines with the bionic 18.04 distribution... The generated reg_tifs are different from our prior output reg_tifs. This can be reproduced by running the full pipeline tests on any ubuntu 18.04 machine (even on [travis](https://travis-ci.org/github/chriski777/suite2p/jobs/717396488); our current builds are on the xenial 16.04 dist and these builds work fine). This may be relevant to folks that develop/run our tests on 18.04

**Comment by nickdelgrosso** [comment]
Interesting.  Can you provide more details on these differences?  Are these minor (i.e. small rounding differences, but final result is the same) or major differences (assorted python errors or failure to properly register/detect/extract)?

**Comment by chriski777** [comment]
I'll have to test more thoroughly to be sure but the differences seemed to be minor. No errors or anything like that occurred within the pipeline. The comparisons failed when the tests reached the generated tifs.

**Comment by nickdelgrosso** [comment]
Any updates on this bug?

**Comment by chriski777** [comment]
Not really, other than checking that the issue still [persists](https://travis-ci.org/github/chriski777/suite2p/jobs/721829377) on the `main` branch. The linked `bionic_check` branch just contains the main branch with a modified `.travis.yml` to use the bionic distribution on travis CI. I haven't made much progress investigating this and won't be able to so it'd be great if someone else could pick this up.

**Comment by nickdelgrosso** [comment]
Sounds good.  I'll add bionic as a seperate build so we can monitor the situation there in an ongoing way--I think we'll be able to track down what's happening there eventually.

**Comment by nickdelgrosso** [comment]
I've been working on this issue and have been unable to recreate the bionic environment and get the same failures (see my Vagrant virtual machine builds at https://github.com/MouseLand/suite2p/tree/issue-bionic in order to even begin exploring this issue.  Both the mac and linux bionic travis builds only fail at a single full-pipeline integration test, indicating some kind of small library, precision, randomization algorithm, etc difference, but the source of the difference won't be discoverable until it can be reproduced in an interactive environment.
