### ISSUE TITLE
importlib_metadata.PackageNotFoundError

### ISSUE THREAD

**Issue by horsto** [MouseLand/suite2p#521]
Hi! Running the latest version of suite2p I run into the following error: 

```
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\suite2p\lib\site-packages\importlib_metadata\__init__.py", line 575, in metadata
    return Distribution.from_name(distribution_name).metadata
  File "C:\Users\horsto\AppData\Local\conda\conda\envs\suite2p\lib\site-packages\importlib_metadata\__init__.py", line 215, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for suite2p
```
This errors occurs in https://github.com/MouseLand/suite2p/blob/f8fb199b7b7f8901d31e27e398a9c905eda0f2a7/suite2p/version.py#L4

**Comment by nickdelgrosso** [comment]
Hi @horsto, thank you for your report!  

I think this may be stemming from there being multiple installations of suite2p on your conda environment path, but I'm not sure.  Could you please try a fresh installation of both the conda environment and suite2p and try the following command, and we can check if it works (terminal code below):

Creating a completely fresh suite2p install:
```
git clone https://github.com/MouseLand/suite2p
cd suite2p
conda env remove --name suite2p
conda env create -f environment.yml
conda activate suite2p
pip install suite2p
```

Testing if suite2p works (should print "suite2p v0.9.0"):
```
suite2p --version
```

**Comment by nickdelgrosso** [comment]
A "softer" version of this would be to go into the existing suite2p conda environment and delete all the non-0.9 suite2p folders and files:

  1. Find your suite2p conda environment folder:  `conda env list`
  2. Use the file explorer / finder to go to the folder listed next to "suite2p" and search in those folders for the suite2p installation (may be in subfolders called lib, Lib, site-packages, etc.  Different location depending on operating system and suite2p installation method used).
  3. Delete everything called suite2p without an 0.9 next to it.  If unsure, just delete all of the suite2p files and folders and reinstall with pip: `pip install suite2p`.

This method may work if you have a lot of non-suite2p related dependencies mixed into the same environment, or have a custom environment or lots of plugins.  The approach listed above (creating a completely-fresh conda environment), though a bit tedious, should always work.

**Comment by horsto** [comment]
Thanks a lot for your thorough reply @nickdelgrosso! Starting from scratch with the suite2p env did the trick!

**Comment by nickdelgrosso** [comment]
That's great to hear!

**Comment by simon-ball** [comment]
>I think this may be stemming from there being multiple installations of suite2p on your conda environment path, but I'm not sure. Could you please try a fresh installation of both the conda environment and suite2p and try the following command, and we can check if it works (terminal code below):

I ran across this issue myself, on a freshly minted Ubuntu 20.04 VM (where there were, unquestionably, zero other installations of suite2p). The problem is _not_ due to multiple installations of Suite2p - it's due to _not enough_ installations.

Suite2p relies on a few dependencies that are not available via `conda`, which are enumerated in `setup.py`, and can only be installed via pip. It also enumerates a few dependencies which _are_ available via `conda`, although only via non-default channels. This necessitates the `pip install suite2p` step, which is no longer included in the `environment.yml` file, but probably should be (and I think was in the past). 

As it stands right now, you cannot do the following:
```
conda env create -f environment.yml
conda activate suite2p
python -c "import suite2p"
```
without error, due to those missing dependencies, it _requires_ (the user) to add an extra line during installation.
```
conda env create -f environment.yml
conda activate suite2p
pip install suite2p
python -c "import suite2p"
```

As far as core dependencies go, the following deps are missing from `environment.yml`, which can be fixed via `pip install suite2p`. Personally, I would advise moving those that _can_ be handled via `conda` into `environment.yml`, bcause the less you mix up `conda` and `pip`, the better. It would also provide a more sensible separation between dependencies that _require_ `pip` (either because unavilable anywhere else, or to take advantage of `pip`'s nice `extras` feature) and those that do not, since `conda` is now the only way to install all of the necessary dependencies (1)
* `paramiko` (available via the `anaconda` channel)
* `importlib_metadata` (available via the `conda-forge` channel)
* `tifffile` (`conda-forge`)
* `pyqtgraph` (`anaconda`)
* `natsort` (`anaconda`)

`rastermap` and `scanimage-tiff-reader` are not available via `conda`. They could be included as `pip` dependencies (as can suite2p itself) in the environment.yml file, or just left in `setup.py` along with the extended dependencies (which conda doesn't really support, even if the actual packages are available via conda)

That would change the `environment.yml` file to:
```
name: suite2p
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python>=3.7
  - pip
  - mkl_fft=1.0.10
  - mkl=2019.3
  - numpy>=1.16
  - numba>=0.43.1
  - matplotlib
  - scipy
  - h5py
  - scikit-learn
  - pyqt
  - paramiko
  - importlib_metadata
  - tifffile
  - pip:
    - suite2p
```

(1) A recent suite2p change broke backwards compatibility with Python 3.6, while Intel hasn't updated its `mkl` and `mkl_fft` wheels in a couple of years, and they are not forward compatible with Python 3.7

**Comment by nickdelgrosso** [comment]
Good points, @simon-ball--the installation steps for suite2p did change this summer.  #522  has the pip portion of the dependency list going back into the environment.yml file as you suggested, but installing suite2p as an explicit step (either by `pip install suite2p` or `python setup.py install` from the suite2p directory, after installing the conda dependencies) remains, and is described in the docs.
