### ISSUE TITLE
Issues with merge

### ISSUE THREAD

**Issue by ransona** [MouseLand/suite2p#551]
Hi

I've been trying to use the merge feature and there are a few things which might be bugs or my misunderstanding.

1) When suggesting merges sometimes it suggests merging the same ROI several times into a single new merged ROI like this (roi 88 suggested twice in the same merge suggestion):
![image](https://user-images.githubusercontent.com/7849066/94661618-98508400-0307-11eb-95b5-e980a3474669.png)

2) After loading the Fall.mat file in Matlab some of the merged ROIs seems to contain the same 'original' ROIs. For example in the attached Fall.mat file ROIs 88 upwards are all merges. You can see that 88 and 96 both have the same imerge fields ([13,14,17]).

3) In the example above if you open stat{13} its 'inmerge' field value is 93 but ROI 93's imerge field is [18,23].

4) In the GUI after merging and then selecting an roi which has been merged with another, sometimes the selection comes up labelled/filled in white and sometimes in grey - does this indicate something?
white example:
![image](https://user-images.githubusercontent.com/7849066/94661868-e6fe1e00-0307-11eb-8eae-a31aaa8f332d.png)
grey example:
![image](https://user-images.githubusercontent.com/7849066/94661940-fc734800-0307-11eb-9af6-9c49d1dbc785.png)

Thanks again for the fantastic software.

Adam

[stat.zip](https://github.com/MouseLand/suite2p/files/5304168/stat.zip)

**Comment by carsen-stringer** [comment]
I implemented this in a weird way where the suggestion indices were replaced with the merged ROI (if the indices were merged), so behavior like that could occur. Computing the new suggested merges is not too slow so instead after each merge this now occurs and this behavior will no longer occur. The gray is happening because the GUI is not properly removing the merged ROI when adding a new merged ROI. Hopefully that also won't happen if it doesn't suggest to merge the ROI with itself.

You can try the new functionality on the dev branch:
```
git clone https://github.com/MouseLand/suite2p.git
cd suite2p
git fetch origin
git checkout dev
python -m suite2p
```

**Comment by ransona** [comment]
Ok thanks will try this.
