### ISSUE TITLE
undefined problem in estimating spatial scale v0.9.2

### ISSUE THREAD

**Issue by djkapner** [MouseLand/suite2p#554]
I am migrating from 0.7.5 to the latest version, and I see a change in behavior.

In 0.7.5 this printed error could come about if the mode of the spatial scale estimator was 0:
https://github.com/MouseLand/suite2p/blob/7bbbf57815c4aaac19ead79e1d31565663687f3b/suite2p/extraction/sparsedetect.py#L440-L441
In fact, that condition was probably never reached, because, when populating `I`, `I[0]` is never populated, since the loop starts at 1:
https://github.com/MouseLand/suite2p/blob/7bbbf57815c4aaac19ead79e1d31565663687f3b/suite2p/extraction/sparsedetect.py#L421-L427

In the latest version, the for loop has been replaced by an iterator, where `I[0]` is populated:
https://github.com/MouseLand/suite2p/blob/17501ef3d4f03ec4c6ca89d3b9186078a640c4f6/suite2p/detection/sparsedetect.py#L307-L313

Now, the printed error can be reached, except it is no longer just printed, but it raises an Exception. In my case (Allen Institute data), this means the new version fails on 15% of our experiments.

I can re-establish the old behavior, by adding `I[0] = 0.0` after the iterator.

The issues that I am raising are:
* the behavior has changed. It is not clear from the [commits](https://github.com/MouseLand/suite2p/commit/7d71d34ef18046bfe5336bb4ea23037416f757d4#diff-8d6d0a1443eed93e09419dbed8289e10) whether this was a bug fix, or inadvertent.
* in the old version, it seemed there was some fall-back setting intended, because even if the mode somehow ended up being `0`, then the threshold scaling parameter was still set and the processing continued. With the Exception, the processing stops.
https://github.com/MouseLand/suite2p/blob/7bbbf57815c4aaac19ead79e1d31565663687f3b/suite2p/extraction/sparsedetect.py#L444
* The text in the exception is not very informative to the user. `Everything should break now.` With the older version, I could successfully segment the 15% of our experiments that are failing now. Reading your wiki, it seems a suggestion might be "if it fails, manually set the spatial scale." I think the Exception should state that if that is the intent. Currently, the user doesn't know much about what happened.
* On the other hand, we are attempting to implement this code in an automated pipeline. It would be much preferable for the code to log a warning that it could not establish a spatial scale and that processing will proceed by falling back on some default setting (1, perhaps, as that seems to be the intent in the older version.)

**Comment by nickdelgrosso** [comment]
Hi @djkapner,

Thank you for the descriptive report.  Yes, raising errors instead of print statements in many places is a change from the old version that helps prevent intractable errors from propagating through the pipeline and help discover problems when they arise, and you're certainly correct that the error message is not very helpful.  As the person who made the change originally, it was not clear what the best way to handle that case (`im == 0`), and it doesn't seem to arise in any of our test data, but now there is a good opportunity to discuss it.  

It seems like we have a few different options for handling this--you suggested a few good ones.  How about this as a solution: 
 Set the spatial scale to a default value (1 seems to be the suggestion) if the algorithm calculates it to be 0, and continue from there.  A warning could also be issued to inform the user that no better option was found.  This would be implemented as something like this:

```python
if im == 0:
   im = 1
   warn("Spatial scale estimation failed.  Setting spatial scale to 1 in order to continue.  To use a different value, set it in ops['spatial_scale']")
```

Additionally, a `ops['spatial_scale_default']` parameter could be introduced, so that researchers can override it to something else in case they find a different scale tends to work best for their data.

Thoughts?  It seems to me that this would work well with your pipeline.

Best wishes,

Nick

**Comment by djkapner** [comment]
@nickdelgrosso Thanks for the reply. Your 3 suggestions sound like they would work well for us:
* warn instead of fail
* default to 1 if 0 is reached
* unless a new parameter is provided, in which case default to this setting.

Once implemented, could you tag the commit? This will help us nail down that we're conducting a production run of analysis with, for example, `v0.9.3` of Suite2P. 

Best,
Dan

**Comment by nickdelgrosso** [comment]
@djkapner Sounds good.  

@carsen-stringer @marius10p Comments?

**Comment by carsen-stringer** [comment]
Sounds great, thanks Nick!

**Comment by nickdelgrosso** [comment]
@djkapner fix is in pull request stage now.  I ended up not including a way to set the default spatial scale, because implementing would introduce some confusion with the existing spatial_scale ops setting, so it defaults to 1 like discussed.  It should be in the next suite2p release.

**Comment by djkapner** [comment]
> @djkapner fix is in pull request stage now. I ended up not including a way to set the default spatial scale, because implementing would introduce some confusion with the existing spatial_scale ops setting, so it defaults to 1 like discussed. It should be in the next suite2p release.

Awesome! Is there a roadmap for timing of the next release?

**Comment by nickdelgrosso** [comment]
I can't say when the next release will be (depends on everyone's schedule, and some manual testing of the latest changes), but I'd guess in the next couple of weeks.  If you are watching the repository, you'll get an alert when it happens.

**Comment by carsen-stringer** [comment]
this is in the current release so I'm going to close this issue
