### ISSUE TITLE
OMP error

### ISSUE THREAD

**Issue by tjoy20** [MouseLand/suite2p#563]
Hi, I recently switched from  running suite2p on a windows to a mac. On a mac, I get the following error when I try to run suite2p. 
OMP: Info #270: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

Is there a way around this? Thanks.

**Comment by nickdelgrosso** [comment]
Hi @tjoy20 ,

It sounds like an OpenMP warning (not an actual error as such; that's what the `Info` part means) that is related to the version of OpenMP installed on your system interacting with the installed C++ compiler (as explained [here](https://syten.eu/docs/faq.html#faq_omp_nested)).  It could be that making a new conda environment and reinstalling suite2p via the environment.yml file will get the right version of OpenMP, but unless it is stopping suite2p from running, it should be something that can be safely ignored.

Otherwise, is suite2p running okay on your computer?

Best wishes,

Nick

**Comment by tjoy20** [comment]
Hi Nick, Thanks so much for the prompt response. I installed via the environment. Good news is that suite2p is running fine- but it was really slow and I thought it was due to the OMP error, but figured it was because my files were on a network drive. Importing the files to a local drive fixed the issue and I guess I can safely ignore OMP.

**Comment by nickdelgrosso** [comment]
That's great!  Glad it worked out.  Closing the issue.
