### ISSUE TITLE
Is there a way to read only certain frames of a tiff file in Suite2p?

### ISSUE THREAD

**Issue by hhhaoli** [MouseLand/suite2p#595]
Hi ! 
First of all, thanks much for this powerful tool! Works quite well.
Just wondering is there a way to read and analyze a specified sequence of frames within a tiff file? For example in my case, data from different z-axis are bundled in one tiff file; x frames are collected at each z-plane before going to the next z-plane, so images from different planes are not interleaved in the saved data (from ScanImage). It will be great if suite2p can read and analyze the 1,2,...,n th chunk of x frames separately. Not sure if this is doable in the suite2p GUI. 

Thanks a lot!

**Comment by carsen-stringer** [comment]
sorry this is not something we plan on supporting. I'd recommend splitting the tiffs into separate planes and process each one separately. 

because the planes are collected at different times it doesn't make sense to analyze them in the same way as interleaved (fluorescence from one plane is not nearby in time with other frames like in the interleaved case)
