### ISSUE TITLE
Neuropil extraction and display

### ISSUE THREAD

**Issue by marcelbvv** [MouseLand/suite2p#613]
When analyzing recording where there is a high density of cells, I've seen that the neuropil sometimes includes the activity of a neighboring cell and sometimes has a higher level of activity than the ROI. This causes the neuropil corrected fluorescence (F-0.7*Fneu) to be negative. 
1- How do you handle these cases?
2- Is there some way to exclude the neuropil pixels that are also part of an ROI?
3 - I've tried to reduce the 'inner_neuropil_radius' to 1 and 'min_neuropil_pixels' to 100 but there was little improvement. Is there a way to visualize the neuropil area of each cell? There is a plot showing this in the original suite2p paper.

Thanks a lot for your help!
![Overlapping ROIs](https://user-images.githubusercontent.com/27411758/106471756-4335a200-64a2-11eb-8327-3c1343f34519.png)

**Comment by carsen-stringer** [comment]
I'm sorry I think this may have been a bug that was including overlapping pixels in neuropil estimation -- can you try the latest github version? I will make a new pip soon with this fix included. I'm going to close this issue for now but please comment if it's not resolved.

to visualize the neuropil you will have to run some internal suite2p processing:
```
from suite2p.detection.masks import create_neuropil_masks, create_cell_pix

ops = np.load('ops.npy', allow_pickle=True).item()
stat = np.load('stat.npy', allow_pickle=True)
cell_pix = create_cell_pix(stats, Ly=ops['Ly'], Lx=ops['Lx'])   
neuropil_masks = create_neuropil_masks(
            ypixs=[stat['ypix'] for stat in stats],
            xpixs=[stat['xpix'] for stat in stats],
            cell_pix=cell_pix,
            inner_neuropil_radius=ops['inner_neuropil_radius'],
            min_neuropil_pixels=ops['min_neuropil_pixels'],
        )
```

we don't save it anymore because it can be pretty large
