### ISSUE TITLE
what exactly do F and Fneu content mean？

### ISSUE THREAD

**Issue by laopenti** [MouseLand/suite2p#627]
Hi Carson,

First，I wanna thank u for the fantastic job in calcium imaging analysis algorithm development. I am a total novice in neuroscience and algorithm&.code. During the last 3 months, I have waded to try to understand the underline meaning further with practicing it.

Anyway, since I have made the very point where `fall.mat` showed up, there is a question confusing me that obstruct the next processing and plotting the results of the analysis.
that is, what exactly do F and Fneu content mean when I load it in Matlab？Dose it represent the values of `Fluorescence` in each ROI area(cells or not cells), or relative to `Frequence`?
![image](https://user-images.githubusercontent.com/65429918/108583201-d3b12500-7372-11eb-94d5-d3bdac7c7652.png)
![image](https://user-images.githubusercontent.com/65429918/108583214-e6c3f500-7372-11eb-994e-cb1c33b698d8.png)

I know the issue might be inaptitude, but it really important for me as a newcomer. One more brusquely requests, would you please do some interpretation for each of the `fall.mat` content as the pic shown above? Cause that really helps us.
Looking forward your soon reply.

Sincerely, Benson

**Comment by LeonardoLupori** [comment]
Hey for a great tutorial check out this page:  
[Tutorial](https://suite2p.readthedocs.io/en/latest/outputs.html)

in brief:
 - `F`:  fluorescence traces for all the cells detected
 - `Fneu`: Neuropil fluorescence for all the cells (typically you subtract a portion of the neuropil signal from the cell trace in order to correct for artifacts)

Note that these are traces for *ALL* the ROIs that the software detected! You most certainly manually removed some of the ROIs from the analysis. The info on the ROIs you ultimately classified as cells is in the `iscell` variable

**Comment by laopenti** [comment]
Hey Leonardo,
Thank you for the warm and precise reminder for the question, it really helped me a lot in understanding the data output from `suite2p`.
Best wishes to you!

**Comment by LeonardoLupori** [comment]
Glad it helped!

I'll also point out this part from the tutorial in case you missed it.
It might save you some headache! :D

>The “iscell” assignments are only saved ONCE when the pipeline is finished running. If you make changes in the GUI to the cell assignments, ONLY iscell.npy changes. [...] Alternatively there is a new save button in the GUI (in the file menu) that allows you to save the iscell again to the Fall.mat file.

Best wishes to you and happy imaging!

**Comment by carsen-stringer** [comment]
thanks @LeonardoLupori for the help!
