### ISSUE TITLE
allow GUI to accept combined file with XY per plane/ROI

### ISSUE THREAD

**Issue by tbenst** [MouseLand/suite2p#655]
When processing multi-plane data, the "combined" output gives (x,y) coordinates that are tiled. I imagine this is convenient for visualization in suite2p, but it makes it difficult to recover the actual (x,y) coordinates of the cells since it's dependent on how the tiling works--I'm actually not sure how to recover the actual (x,y)?

I could look at the individual plane folders, but I'm not sure how to join data from the plane data to the combined data, e.g. intuitively would do a JOIN operation on `iplane` and `med`. I also don't know if it's safe to assume that the ordering of the combined stat files is the concatenation of each plane `stat` file.

The alternative I'm pursuing is to read each plane `stat` file, append the `iplane` key, and concatenate, which I think follows the principle of least surprise and should probably be the default for "combined" output..?

**Comment by carsen-stringer** [comment]
ah yes this is for the GUI visualization -- otherwise we have to do the addition there plane-by-plane for visualization and it's a pain. happy to take a pull request though that does what you're describing for the GUI.

The NWB file is output in the format you're describing, maybe you want to use that instead?

**Comment by carsen-stringer** [comment]
going to close this because the formatting you describe is the same as NWB output from suite2p, and would prefer not to replicate it
