### ISSUE TITLE
NWB save error [NWBFile.__init__: incorrect type for 'session_start_time' (got 'tuple', expected 'datetime')]

### ISSUE THREAD

**Issue by FishQian** [MouseLand/suite2p#659]
Hey I recently got this error when saving NWB.
Everything else is fine when I check the "save NWB" in the opt as 0.
I don't use NWB files but just want to put it here so in case someone else found the same errors.
Any thoughts how to solve this?

Saving in nwb format >>>ERROR<<< Traceback (most recent call last): File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 193, in _run_module_as_main 
>>>ERROR<<< 
"__main__", mod_spec) File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/runpy.py", line 85, in _run_code >>>ERROR<<< 
exec(code, run_globals) File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 78, in <module> 
>>>ERROR<<< 
main() 
File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/__main__.py", line 71, in main run_s2p(ops, db) 
File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/run_s2p.py", line 442, in run_s2p 
>>>ERROR<<< 
io.save_nwb(save_folder) 
File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/suite2p/io/nwb.py", line 172, in save_nwb else datetime.datetime.now()) 
File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/hdmf/utils.py", line 579, in func_call 
>>>ERROR<<< 
pargs = _check_args(args, kwargs) 
File "/Users/fish/opt/anaconda3/envs/suite2p/lib/python3.7/site-packages/hdmf/utils.py", line 572, in _check_args >>>ERROR<<< 
**raise ExceptionType(msg) 
TypeError: NWBFile.__init__: incorrect type for 'session_start_time' (got 'tuple', expected 'datetime') Interrupted by error (not finished)**

**Comment by carsen-stringer** [comment]
oh no! I guess NWB formatting changed again, @rly is there an update to time formatting?

@fishqian try `pip install pynwb==1.4.0` that version is what the tests were run with

**Comment by FishQian** [comment]
> oh no! I guess NWB formatting changed again, @rly is there an update to time formatting?
> 
> @FishQian try `pip install pynwb==1.4.0` that version is what the tests were run with

Hey Carsen!

Unfortunately, my current version of pynwb is 1.4.0 already, and this didn't solve the issues.
Any thoughts on other alternatives?

Thanks,
Fish

**Comment by rly** [comment]
Hi @FishQian I am one of the NWB developers and will take a look at this. Could you tell me:
1) your Python environment, e.g., the results of `pip list`
2) what OS are you using?

Thanks,
Ryan

**Comment by FishQian** [comment]
> Hi @FishQian I am one of the NWB developers and will take a look at this. Could you tell me:
> 
> 1. your Python environment, e.g., the results of `pip list`
> 2. what OS are you using?
> 
> Thanks,
> Ryan

Hy Ryan,
I'm using MacOS Big Sur, Version 11.2.3
Here is my python env info (they are installed as instructed by the environmental.yml in the github):
`Package               Version
--------------------- -------------------
attrs                 20.3.0
bcrypt                3.2.0
certifi               2020.12.5
cffi                  1.14.5
cryptography          3.4.7
cycler                0.10.0
h5py                  2.10.0
hdmf                  2.4.0
importlib-metadata    3.10.1
joblib                1.0.1
jsonschema            3.2.0
kiwisolver            1.3.1
llvmlite              0.31.0
matplotlib            3.4.1
mkl-fft               1.0.10
natsort               7.1.1
numba                 0.48.0
numpy                 1.18.5
olefile               0.46
pandas                1.2.4
paramiko              2.7.2
Pillow                8.1.2
pip                   21.0.1
pycparser             2.20
PyNaCl                1.4.0
pynwb                 1.4.0
pyparsing             2.4.7
PyQt5                 5.15.4
PyQt5-Qt5             5.15.2
PyQt5-sip             12.8.1
PyQtChart             5.12
pyqtgraph             0.12.1
PyQtWebEngine         5.12.1
pyrsistent            0.17.3
python-dateutil       2.8.1
pytz                  2021.1
rastermap             0.1.3
ruamel.yaml           0.17.4
ruamel.yaml.clib      0.2.2
sbxreader             0.1.5
scanimage-tiff-reader 1.4.1
scikit-learn          0.24.1
scipy                 1.6.2
setuptools            49.6.0.post20210108
six                   1.15.0
suite2p               0.10.0
threadpoolctl         2.1.0
tifffile              2021.4.8
tornado               6.1
typing-extensions     3.7.4.3
wheel                 0.36.2
zipp                  3.4.1`

**Comment by rly** [comment]
Sorry for my delay in response. It looks like a tuple is being passed to `NWBFile.__init__` for the session_start_time instead of a datetime. This hasn't changed in PyNWB/HDMF, so I wonder if there is something unusual with the `ops`, specifically `ops['date_proc']` being passed in to `NWBFile.__init__`.

I was able to reproduce the error, specifically with save_mat=1 and save_NWB=1 in the Run suite2p GUI. It does not occur with save_mat=0 and save_NWB=1. `io.save_nwb()` loads `ops` from an `ops.npy` file that has 'date_proc' as a tuple with a single string. 

```python
>>> ops = np.load('C:/Users/Ryan/Downloads/suite2p/plane0/ops.npy', allow_pickle=True).item()
>>> ops['date_proc']
('2021-05-25 11:18:32.940738',)
```

Searching through the suite2p code base, it looks like `ops['date_proc']` is only ever a datetime, a string, or an empty list, but never a tuple, and I cannot find where it might be converted into a tuple. 

On these lines:
https://github.com/MouseLand/suite2p/blob/bdd7aee9a898c153b7f664b1efe8f3e853662f3f/suite2p/run_s2p.py#L295-L296
when save_mat=1, ops['date_proc'] is converted from datetime to string. Perhaps when it is saved and loaded by numpy or other processes, it is being converted to a tuple with that string. (A string value is also not allowed for session_start_time for `NWBFile.__init__`.) I suggest in the lines above, copying `ops` and modifying the 'date_proc' key in `ops_copy` for the purpose of saving it to a .mat file, or in `save_nwb`, if 'date_proc' is a tuple (or string), converting it back into a datetime.

**Comment by carsen-stringer** [comment]
nice debugging @rly ! I've implemented your fix and added the save_mat=1 option to our NWB saving test
