### ISSUE TITLE
conflicts in dependencies

### ISSUE THREAD

**Issue by chrisroat** [MouseLand/suite2p#664]
The install instructions indicate to use the environment.yml file, which leads to a bunch of conflicts.  Is that still the recommended way to install.

```
$ conda env create -f environment.yml 
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
...
```

**Comment by carsen-stringer** [comment]
I can't reproduce this, what conda version are you using? We have been stuck with an old mkl_fft version because the latest conda version I tested (1.3.0) was giving weird non-deterministic behavior. I'm guessing forcing old mkl versions is the reason for the dependency conflicts? But there's finally a new pip for it: https://pypi.org/project/mkl-fft/!!! 

If you want to test it, pip install mkl_fft==1.3.0 and see if it passes the tests. mkl-fft is currently the only suite2p dependency you have to install from the conda package manager, and it's an important one -- it really speeds up the fft's for registration.

**Comment by chrisroat** [comment]
I am using conda version 4.9.2.

I get the conflict because of the pin on mkl itself, not mkl_fft.   It results from my use of (the recommended) strict channel priority.  If I remove that setting, or change the mkl version from 2019.3 to 2019.5, no conflicts arise.

To be safe, I'll drop the channel priority for this project.  Do you think there be harm in using mkl=2019.5?

**Comment by carsen-stringer** [comment]
I've removed mkl-fft and replaced with torch fft -- this should be a wrapper on the same underlying library, but it seems to be working correctly and is easier to install
