### ISSUE TITLE
GUI bugs

### ISSUE THREAD

**Issue by ransona** [MouseLand/suite2p#671]
Hi 
Just to report a few small bugs I've noticed in the File->Run Suite2P part of the GUI (using the latest version from Github):

1) There is a bug when adding more than 10 experiments to a batch in the GUI. When you add the 10th I get the below error. 
Traceback (most recent call last):
  File "C:\Users\uic\.conda\envs\suite2p2\lib\site-packages\suite2p\gui\rungui.py", line 318, in add_batch
    self.odata[L].setText(self.datastr)
IndexError: list index out of range

2) When you click save ops to file then choose a filename, the prompt reappears asking for the filename to save to again.

3) When you add an experiment in batch mode the options go back to default after each added batch - I expect typically people want to use the same ops for each experiment in a batch.

4) There is an error when no rois are detected in a plane.

Many thanks
Adam

**Comment by carsen-stringer** [comment]
Thanks!
1. If you have more than 10 experiments to run I recommend using a jupyter-notebook, there's only space so much space in that GUI menu, but I've bumped it up to 15.
2. this is fixed in the latest version
3. good point, I've stopped the reset_ops command there, let me know if it causes issues
4. what's the error message?
