### ISSUE TITLE
Package for handling Thorlabs .raw input, haussmeister, cannot be installed by pip

### ISSUE THREAD

**Issue by Mitchellb16** [MouseLand/suite2p#740]
The input [documentation](https://suite2p.readthedocs.io/en/latest/inputs.html) suggests install of the [haussmeister ](https://neurodroid.github.io/haussmeister/) package via pip for automatic handling of Thorlabs .raw files. 

It seems the package is no longer available via pip, and I can't find it in PyPI either. Is there a workaround that would still allow the package to integrate with suite2p's pipeline? This is the error I get when trying:

```
pip install haussmeister
ERROR: Could not find a version that satisfies the requirement haussmeister (from versions: none)
ERROR: No matching distribution found for haussmeister
```

**Comment by kir0ul** [comment]
You could try to install it directly from Git with:
```
pip install git+https://github.com/neurodroid/haussmeister.git
```
Also you may want to open an issue on the [`haussmeister` repository](https://github.com/neurodroid/haussmeister/issues) to ask why they removed it from PyPI.

**Comment by kir0ul** [comment]
> Okay I tried this and ended up having troubles with installing haussmeister dependencies, had to install a SIMA build manually.

Indeed I'm also unable to install `haussmeister` from Git because `pip` is unable to build the `sima` dependency. Apparently there's a similar issue on the `sima` repository that has been open for a while: https://github.com/losonczylab/sima/issues/253

Sorry, I'm not sure how to workaround this issue. In any case it would probably be a good idea to also open an issue on the [`haussmeister` repository](https://github.com/neurodroid/haussmeister/issues).
