### ISSUE TITLE
Suite2p with boutons and cell body in the same FOV

### ISSUE THREAD

**Issue by annahayoon** [MouseLand/suite2p#751]
Hi! 

I have a 0.3um pixel size images that contains boutons and neuron cell body, and I'm trying to do ROI detection with suite2p. Suite2p detects boutons fine, but for our neuron cell body (~35 pixels on the 0.3um pixel size) cannot be detected using the platform despite changing various parameter values--I've tinkered with spatial_scale and snr_threshold. When we resize the images to get us 1um pixel size (which gets us ~10 pixels for the cell body), suite2p ROI detection works well. We are trying to figure out a way to get suite2p ROI detection to work on the original 0.3um pixel size cell body images, and I was wondering if you had any ideas on how to get suite2p to work in our case?

Thanks!

**Comment by carsen-stringer** [comment]
could you try changing the "threshold_scaling" parameter (decrease it) and increase the number of iterations? it may be that the small ROIs have higher variance and they are found first and then the cells are found after

**Comment by generalciao** [comment]
Anna, did you find that Carsen's suggestion solved your issue? Or did you find a different solution that helps you detect multiple classes of ROIs with different sizes?

**Comment by annahayoon** [comment]
We ended up just manually drawing out ROI for one channel, and then using suite2p for the other channel. Please let me know if there are any other suggestions. Thank you!

**Comment by generalciao** [comment]
Thanks for your quick reply. 

From your response it sounds like you have different (color?) channels for your small and large ROI types? 

When I read your first post, I pictured them all intermixed in a single channel. If you have multichannel data, I believe there are some other discussion threads that might be of interest - overall it seems like suite2p considers the 2nd channel as structural, if I understand correctly.

For this type of scenario (or if it's in a single channel as I initially understood), I have been thinking about about running suite2p twice on the same data? File format conversion and registration steps won't repeat, so that's good. I've played around with just moving some of the output data from the first pass (with a given set of parameters) to a different folder, then rerunning on the same source data with some parameters changed. If the parameters are sufficiently different so that the ROIs found in the second pass definitely do not include any found in the first pass, and vice-versa (e.g. no overlap in the ROI populations), it's maybe a useful approach. Not super convenient. Do you have any thoughts / experience with this?
