### ISSUE TITLE
NameError for resample_frames when loading behavioral trace

### ISSUE THREAD

**Issue by generalciao** [MouseLand/suite2p#826]
The GUI menu command "Load behavior or stim trace (1D only)" results in an error for me, when I point it to a .npy file (which I have confirmed loads fine from the Python interpreter prompt).

Error message:
menus.py, line 40, in <lambda>
 parent.loadBeh.triggered.connect(lambda: io.load_behavior(parent))
io.py, line 376, in load_behavior
 parent.beh_resampled = resample_frames(parent.beh, parent.beh_time, np.arange(0, parent.Fcell.shape[1]))
NameError: name 'resample_frames" is not defined

I'm wondering if there this could be due to a mismatch in the number of values in the 1D trace compared to the number of imaging frames? But I believe in that case, a different error message is shown, so this is unlikely. So I'm stumped what resampling of frames this is about.

Is this working correctly for other users? Or you also get this same error? Any workarounds?

**Comment by generalciao** [comment]
This was indeed due to a mismatch in the size of my 1D trace. However, I'm leaving this open for now, because it seems that the function resample_frames is not defined anywhere, and there is still a code path that could result in it being called.

**Comment by chriski777** [comment]
Hi @generalciao, thanks for letting us know about this issue. It turns out this `resample_frames` function is only called in the  `io.py` file that you've described and it seems the `resample_frames` function was accidentally removed in a previous commit. I've added it back to the io.py file to address this NameError issue (#869) . I'll close this issue not now but feel free to reopen this if you still run into issues with the latest release!
