### ISSUE TITLE
Use a custom cellpose model (trained in 2.0) for suite2p segmentation?

### ISSUE THREAD

**Issue by generalciao** [MouseLand/suite2p#846]
You've made lots of improvements to cellpose, now out as version 2.0. I find that I can get better segmentation in the cellpose 2.0 GUI on the mean image from suite2p, than what I get in suite2p with anatomical mode (I'm running suite2p 0.10.2 and cellpose 0.6.5  within the same conda env). 

I'm not sure which cellpose model is being used by suite2p? Is it cyto? I don't see where in the code the So I would like to be able to use an updated cellpose model within suite2p, for example CP or TN1, or even better would be a model fine-tuned by me in cellpose 2.0. Is any of this currently possible?

Alternatively, can I supply a segmentation produced by cellpose 2.0 to suite2p? The workflow would then be something like: run suite2p for registration, run cellpose 2.0 on the resulting mean image, pass the resulting segmentation to suite2p and run suite2p again for signal extraction and deconvolution. Of course I'd prefer to just set a suite2p pipeline parameter pointing to my preferred cellpose model.

Would updating cellpose in my suite2p environment to the latest version cause a different model to be used?

Thanks!

**Comment by superwhat1** [comment]
I have been hoping to use my "person in the loop" cellpose2 trained model for anatomical only ROI detection in suite2p as well. 
The model that anatomical only uses is set in the ops.npy file. You should a ops file from the suite2p GUI with all the settings you want that are modifiable there. Then in a python IDE use:
ops = np.load("FILE_PATH/saved_ops.npy", allow_pickle = True).item()
ops['pretrained_model'] = DESIRED_MODEL 
Since suite2p currently uses the older 1.0.2.dist only cyto, nuclei and cyto2 are available as models.
You can view all the ops settings with "print(ops)"
Some other useful settings to mode in the ops file when running anatomical only are ops['cellprob_threshold'] and ops['flow_threshold'].

**Comment by carsen-stringer** [comment]
yes this is now possible! these parameters are also now available in the suite2p GUI
