### ISSUE TITLE
The identified cells do not overlap

### ISSUE THREAD

**Issue by Jessica0218** [MouseLand/suite2p#851]
Hi，
I have observed that the cells identified by Suite2P GUI do not overlap. Is there any way to make the cells overlap? This allows me to choose not to count shared pixels when extracting calcium signal activity ['ops_allow_overlap'=0], making the signal more accurate.

**Comment by carsen-stringer** [comment]
the ROIs will overlap if the signals do indeed overlap, but if an ROI overlaps more than `ops['max_overlap']` with other ROIs it will be discarded. you can set `ops['max_overlap']=1` to not discard any ROIs due to overlap. then `ops['allow_overlap']=0` (which is the default) ignores overlapping pixels when computing the signals across time. 

maybe I misunderstand the question though, if you're not getting enough ROIs with suite2p you can also lower the `ops['threshold_scaling']` parameter
