### ISSUE TITLE
re-run suite2p with data in a new folder

### ISSUE THREAD

**Issue by camille-lab** [MouseLand/suite2p#868]
Hi, 
First of all, thanks for this amazing tool!
I ran suite2p on some data last year, and now I want to re-run it with my current ops parameters. 
I moved my data in the meantime, so suite2p doesn't recognize the registered data.bin file and wants to reprocess the data from the tiffs.
Is it possible to tell suite2p the folder has changed?
It would be amazing if I could simply change the path of the necessary files ('reg_file' for instance) using Jupyter notebook. 
Thanks again!

**Comment by generalciao** [comment]
I don't know the answer to the exact question you are asking. Hopefully there is a way to do what you want exactly. Workaround:

But it is possible to re-run suite2p with changed ops parameters without having to repeat all pipeline steps again (for example if the ops parameters related to registration have not changed): this works when the folder structure remains the same and the stat.npy file is present in the expected output directory. 

For example, in your suite2p/plane0 directory, move all contents into a subdir suite2p/plane0/save1 and then copy the stat.npy file back to suite2p/plane0/stat.npy, then run with new ops parameters. It's been a while since I did the troubleshooting on this, so hopefully I'm not forgetting anything I did to make it work for me.

**Comment by generalciao** [comment]
Addendum: of course, on most operating systems you can create a link so that the moved files appear to still be where they used to / need to be, while avoiding a potentially slow file transfer. I haven't tried doing that for suite2p data files, but let us know if you do!

**Comment by camille-lab** [comment]
@generalciao creating a hard link to the folder (called junction in windows) did work!
Thanks a lot for the tip!
