### ISSUE TITLE
Values when exporting to .csv differ from F.npy

### ISSUE THREAD

**Issue by suryadi-t** [MouseLand/suite2p#877]
Hi, I have a question on exporting raw fluorescence traces to .csv via trace view in the GUI. I did this by selecting a subset of ROIs via draw selection, selecting F for activity mode, followed by right clicking the trace view -> export -> CSV from plot data. Later on, when I compared with the values in F.npy, I saw that the mean value for each ROI occupy completely different intervals. Specifically, those in F.npy have mean values >44, while those in the .csv all have mean values <20. This seems to imply that the values exported to .csv are completely different from those in F.npy. Could you tell me why this is the case? Thank you!

Some further info: while I did select activity mode to be F, I checked the .csv values against spks.npy to be safe and similarly, the values are generally different. Fneu is identically zero in this case as I set neuropil_extract to be 0 when processing the recording.

**Comment by chriski777** [comment]
Hi @suryadi-t, Yep, that is right. The values for the ROIs in the .csv are different because if there are at least 2 ROIs selected, additional transformations are made to the traces to make them easier to plot. If you would like to access the raw fluorescence traces, you can keep track of the ROI indices you select and index the `F.npy` array.
