### ISSUE TITLE
suite2p no longer works in google colab

### ISSUE THREAD

**Issue by jeromelecoq** [MouseLand/suite2p#895]
1. google colab is currently using Python 3.7.15 (as of today when I launch notebooks in US West Coast). 
2. The use of the keep dims option of mode : https://github.com/MouseLand/suite2p/blob/b90025b84d24ac4d1847717bc6e454f9c1ca90f9/suite2p/detection/sparsedetect.py#L256
makes it so that scipy>1.9 is now required to run suite2p. 
3. scipy>1.9 is not available under Python 3.7.15

**Comment by jeromelecoq** [comment]
!pip install suite2p==0.10.1 fixes this issue

**Comment by thomasdeneux** [comment]
!pip install suite2p==0.11.0 is a little better because it prevents some warning messages to show up!

**Comment by thomasdeneux** [comment]
But later on in the notebook the registration_wrapper, detection_wrapper, extraction_wrapper do not exist in version 0.11.0 or earlier versions.

**Comment by chriski777** [comment]
Hi @jeromelecoq, thanks for letting us know about this, and sorry for the late reply. It seems now that Google Colab runs off Python 3.8 (the change was made a week or two after this issue was made) so the newest version of suite2p works on Colab! I'll close this issue now but please feel free to re-open it if you run into any other issues on Colab!
