### ISSUE TITLE
Using ImageJ ROIs to train classifier

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#93]
Is it possible to input ROIs generated with ImageJ to the classifier?

Or convert the .zip files with the coordinates to iscell.npy files?

**Comment by marius10p** [comment]
No, sorry, and even if it was possible, I don't think it would work very well. The ROIs are determined in a way that takes into account the activity, so that the precise patterns of pixel brightness is used as a weight in the mask. In general, ROIs can have all sorts of weird shapes. Furthermore, the classifier needs both positive and negative examples, because it's trying to distinguish pipeline output that is a cell from output that is not a cell.
