### ISSUE TITLE
Clean up/remove folders fast_disk when stopping pipeline

### ISSUE THREAD

**Issue by hummuscience** [MouseLand/suite2p#94]
Found out that stopping the pipeline in the GUI leaves behind a folder in the fast_disk.

When I wanted to re-run the dataset, the pipeline got stuck after computing the reference frame.

It only continued once I removed the folder in the fast_disk

Is that intended behavior?

**Comment by carsen-stringer** [comment]
Hmm yeah if you stop the pipeline before the binary finishes writing then it will error. This is because the pipeline looks for the bin file and it finds it, even though it's no good. If you let it finish writing, then this shouldn't happen. You should be able to restart the pipeline from any time after that point.

**Comment by Cumol** [comment]
Maybe add it as info in the Wiki?

**Comment by Cumol** [comment]
I was running multiple experiments through the pipeline using the same fast_disk but different directories for the expeirments (fast_disk is an ssd while the files are on a HDD).

When going through the results I noticed that I forgot to adjust a parameter, so I adjusted it and re-ran all the files. When the pipeline ran, it said that it is skipping registration because it found a .bin file. I didn't think much of it because I thought that the it did indeed do the registration.

When I checked the re-ran experiments, they all showed the same field of view. That of the last experiment ran (before the re-run). What happened (I think) was that it used the .bin file that was still present in the fast_disk and ran the pipeline on it, instead of rerunning every experiment.

I am testing that with setting delete_bin to True. It might be something that others will encounter too, when running in batch and using a fast_disk

**Comment by carsen-stringer** [comment]
Yes suite2p makes the SAME folder called "suite2p" in the folder you provide for "fast_disk". So then suite2p goes to that SAME folder for each experiment and overwrites the data.bin.

What I recommend doing is when you add "fast_disk" (in the GUI) is to make a new folder with the experiment name and use that.

Or if you're in a jupyter-notebook , you can just say the name of the folder with the experiment name and suite2p will make the folder for you when the pipeline runs

sorry about this :( I will add this information to the wiki
