### ISSUE TITLE
Drawing ROIs manually

### ISSUE THREAD

**Issue by Cumol** [MouseLand/suite2p#96]
I think it would be a good enhancement to be able to draw ROIs manually.

Currently my only problems with the pipeline are that it merges cells together into a single ROI or marks only a small part of a cell as ROI.

Manually drawing ROIs could solve both issues. Separating two rois, or merging multiple smaller ROIs (that are usually not compact).

Are you planning to implement something like it?

P.S: Excuse the amount of github issues I am opening. I am only excited to find a pipeline that seems to work well with my data :) thank you for your work!

**Comment by marius10p** [comment]
Can you post some pictures from the GUI for your data? A simple parameter change might fix your problem, but we need to see the ROI view, the correlation view and the mean image at the minimum.

**Comment by marius10p** [comment]
Thank you. Is this a slice? If so, I would imagine a lot of the activity is synchronous, and some nearby cells might be so strongly electrically coupled that their activity is very similar, in which case there is nothing we can do since Suite2p is an activity-based algorithm. 

We will not be adding manual drawing of ROIs, because that's counterproductive, subjective and requires the user to re-run code to extract fluorescence traces again for all ROIs. You are better off just ignoring the few that have been merged, or treating them as a single ROI, since it would be too much manual work for you to draw ROIs individually. We will probably add a merge button though. 

It also looks like you could play with the settings a little more. Try increasing ops.ThScaling. Decreasing diameter will also result in fewer merges. If you keep getting those halos around cells, you should consider setting ops['max_overlap'] = 1.0 and ops['allow_overlap'] = 1, otherwise cells overlapping their own halos will be thrown out. 'allow_overlap' is not yet exposed in the GUI options, but I'll make a note to put it there. We will also stop updating the pip installs so frequently, so for the latest code, download the github repository and run python -m suite2p from inside the Github folder.

**Comment by Cumol** [comment]
Thank you for the quick response.

Actually this is a neuronal culture. And one of the stimuli is HighK, which usually leads to all of the cells responding at once. Is there a way to make the extraction run on a part of the video only (the stimuli that should be different)?

I will try to go down with the diameter and wait for the merging option as that was the main problem with a smaller diameter. I will also play around with the ThScaling.

I noticed that some things are missing in the normal pip install so I switched to the github version a few days ago :)

**Comment by Cumol** [comment]
@marius10p I was playing around with all the options and I wonder if it is possible to implement passing a range of images to use for ROI extraction? The high correlation is mainly due to the cells responding to a stimulus the activates all of them at once. When I run a video missing these frames the ROI detection is much better.

**Comment by marius10p** [comment]
There is no way to pass in a range of images for ROI detection. 

If these cells have processes and the sensor is not restricted to soma, then you do have contamination from the Z-axis. And if you don't it shouldn't matter, nothing will be estimated. Easiest way to tell is to look in the GUI and see if the background trace has any structure that you can still see in the cells.

**Comment by carsen-stringer** [comment]
I'm going to close this issue because I think the sparse_mode solves at least some of these problems.
